run-mode: replace
source-paths:
- libs
- services
template-paths:
- headroom-templates
variables:
  organization: Wire Swiss GmbH
  email: opensource@wire.com
  project: This file is part of the Wire Server implementation.
  year: '2020'
license-headers:
  haskell:
    put-after: ["^{-#"]
    line-comment:
      prefixed-by: "--"
