resolver: lts-14.27

packages:
- libs/api-bot
- libs/api-client
- libs/bilge
- libs/brig-types
- libs/cargohold-types
- libs/cassandra-util
- libs/extended
- libs/federation-util
- libs/galley-types
- libs/gundeck-types
- libs/imports
- libs/metrics-core
- libs/metrics-wai
- libs/ropes
- libs/sodium-crypto-sign
- libs/ssl-util
- libs/tasty-cannon
- libs/types-common
- libs/types-common-aws
- libs/types-common-journal
- libs/wai-utilities
- libs/zauth
- services/brig
- services/cannon
- services/cargohold
- services/federator
- services/galley
- services/gundeck
- services/proxy
- services/spar
- tools/api-simulations
- tools/bonanza
- tools/db/auto-whitelist
- tools/db/migrate-sso-feature-flag
- tools/db/service-backfill
- tools/makedeb
- tools/stern

nix:
  shell-file: stack-deps.nix


# HaskellNet, HaskellNet-SSL, bloodhound, multihash and stm-hamt have bounds
# issues. We didn't catch those before because in snapshot files, allow-newer:
# true seems to be the default. We should fix these bound issues (we have a
# fork of multihash for this reason already) but for now we just ignore the bounds
allow-newer: true

extra-deps:
- swagger2-2.4
- git: https://github.com/fimad/prometheus-haskell
  commit: 2e3282e5fb27ba8d989c271a0a989823fad7ec43
  subdirs:
  - wai-middleware-prometheus
  # wai-middleware-prometheus can be pulled from hackage once the
  # a version > 1.0.0 of wai-middleware-prometheus is available
  # (required: https://github.com/fimad/prometheus-haskell/pull/45)
- git: https://github.com/wireapp/saml2-web-sso
  commit: 54cc6b14a1bcc27aec630ccdaaf45a4ed9efe0be  # master (Mar 25, 2020)
- git: https://github.com/wireapp/hscim
  commit: 2909c81a0aa4bd4c2c21acafa64b2f744f787df6  # master (Mar 27, 2020)
- ormolu-0.0.3.1
- ghc-lib-parser-8.8.2.20200205@sha256:343f889f7b29f5ec07cf0d18d2a53f250fa5c002b6468a6a05b385d0191b8d34,8408  # for ormolu-0.0.3.1
- git: https://github.com/bitemyapp/bloodhound
  commit: c6233c493b1a7c3df8099872bbc1f66c5f25d95f

- git: https://github.com/kim/hs-collectd
  commit: 885da222be2375f78c7be36127620ed772b677c9
