apiVersion: v1
kind: ConfigMap
metadata:
  name: "federator"
  labels:
    wireService: fedrator
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  federator.yaml: |
    federatorInternal:
      host: 0.0.0.0
      port: {{ .Values.service.internalFederatorPort }}

    federatorExternal:
      host: 0.0.0.0
      port: {{ .Values.service.externalFederatorPort }}

    {{- with .Values.config }}

    logNetStrings: True # log using netstrings encoding:
                        # http://cr.yp.to/proto/netstrings.txt
    logFormat: {{ .logFormat }}
    logLevel: {{ .logLevel }}


    {{- with .optSettings }}
    optSettings:
      setFederationStrategy:
        {{- if .setFederationStrategy.allowAll }}
        allowAll:
        {{- else if .setFederationStrategy.allowedDomains }}
        allowedDomains:
          {{- with $domain := .setFederationStrategy.allowedDomains }}
          - {{ $domain | quote }}
          {{- end }}
        {{- else }}
        # In gotemplate there is no way to distinguish between empty list and no
        # list, we assume empty list when there is no list
        allowedDomains: []
        {{- end}}
    {{- end }}
  {{- end }}
