defaults:
  local: ../../package-defaults.yaml
name: federator
version: '1.0.0'
synopsis: Federation Service
category: Network
author: Wire Swiss GmbH
maintainer: Wire Swiss GmbH <backend@wire.com>
copyright: (c) 2020 Wire Swiss GmbH
license: AGPL-3
dependencies:
- aeson
- base
- bilge
- brig-types
- bytestring-conversion
- data-default
- dns
- dns-util
- email-validate
- errors
- exceptions
- extended
- galley-types
- HsOpenSSL
- HsOpenSSL-x509-system
- http-client
- http-client-openssl
- http-types
- imports
- lens
- metrics-core
- metrics-wai
- QuickCheck
- resourcet
- servant
- servant-client
- servant-client-core
- servant-server
- servant-swagger
- ssl-util
- string-conversions
- text
- tinylog
- types-common
- uuid
- wai
- wai-utilities
- warp
- wire-api-federation
library:
  source-dirs: src
executables:
  federator:
    main: Main.hs
    source-dirs: exec
    ghc-options:
    - -threaded
    - -with-rtsopts=-N1
    - -with-rtsopts=-T
    - -rtsopts
    dependencies:
    - base
    - federator
