defaults:
  local: ../../package-defaults.yaml
name: federator
version: '1.0.0'
synopsis: Federation Service
category: Network
author: Wire Swiss GmbH
maintainer: Wire Swiss GmbH <backend@wire.com>
copyright: (c) 2020 Wire Swiss GmbH
license: AGPL-3
extra-source-files:
- federator.proto # TODO move this file to subfolder?
dependencies:
- QuickCheck
- aeson
- http-types
- async
- base
- bilge
- bytestring-conversion
- data-default
- dns
- dns-util
- email-validate
- errors
- exceptions
- extended
- http-client
- http2-client
- imports
- lens
- metrics-core
- metrics-wai
- mtl
- mu-grpc-client
- mu-grpc-server
- mu-protobuf
- mu-rpc
- mu-schema
- resourcet
- servant
- servant-client
- servant-mock
- servant-server
- servant-swagger
- string-conversions
- template-haskell
- text
- tinylog
- types-common
- uuid
- wai
- wai-utilities
- warp
- wire-api
- wire-api-federation

library:
  source-dirs: src
executables:
  federator:
    main: Main.hs
    source-dirs: exec
    ghc-options:
    - -threaded
    - -with-rtsopts=-N1
    - -with-rtsopts=-T
    - -rtsopts
    dependencies:
    - base
    - federator

  federator-integration:
    main: Main.hs
    source-dirs: test/integration
    dependencies:
    - federator
    - tasty
    - tasty-hunit
    - hspec
    - random
    - cryptonite
    - mtl
    - retry
    - optparse-applicative
    - types-common
    - yaml
    - bytestring

tests:
  federator-tests:
    main: Main.hs
    source-dirs: test/unit
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - federator
    - tasty
    - tasty-hunit
    - yaml
    - bytestring
