defaults: 
  local: ../../../package-defaults.yaml
name: count-team-owners
version: '1.0.0'
synopsis: Count team owners
category: Network
author: Wire Swiss GmbH
maintainer: Wire Swiss GmbH <backend@wire.com>
copyright: (c) 2020 Wire Swiss GmbH
license: AGPL-3
ghc-options:
- -funbox-strict-fields
- -threaded
- -with-rtsopts=-N
- -with-rtsopts=-T
- -rtsopts
dependencies:
- base
- bytestring
- bytestring-conversion
- cassandra-util
- conduit
- containers
- galley-types
- imports
- lens
- metrics-core
- optparse-applicative
- prometheus-client
- text
- time
- time-compat
- tinylog
- types-common
- unliftio
- uuid
- wai-middleware-prometheus
executables:
  count-team-owners:
    main: Main.hs
    source-dirs: src
