apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    wireService: ldap-scim-bridge
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}